"""Deterministic execution contracts for PureSaber."""

from quant_execution.artifacts import (
    ArrowReplayArtifactSink,
    StoredRunArtifacts,
    load_stored_artifacts,
)
from quant_execution.broker import DeterministicBroker, remaining_quantity
from quant_execution.contracts import (
    AccountSnapshot,
    Fee,
    Fill,
    Funding,
    LedgerEvent,
    LedgerEventType,
    LedgerTransaction,
    LiquidityRole,
    Order,
    OrderEvent,
    OrderIntent,
    OrderStatus,
    OrderType,
    PortfolioRiskSnapshot,
    PositionRiskSnapshot,
    Posting,
    RiskCheckContext,
    RiskDecision,
    RunResult,
    Settlement,
    Side,
    TimeInForce,
)
from quant_execution.engine import (
    DeterministicRunEngine,
    ReplayError,
    RunArtifacts,
)
from quant_execution.ledger import ExactAccountLedger
from quant_execution.matching import BarMatchingModel, L2MatchingModel, TradeBBOModel
from quant_execution.protocols import (
    AccountLedger,
    BrokerSimulator,
    MatchingModel,
    PortfolioRiskPolicy,
    RiskGate,
    RunEngine,
    Strategy,
    StrategyContext,
)
from quant_execution.rules import (
    AShareRule,
    CryptoSpotRule,
    FuturesRule,
    LinearPerpetualRule,
    MarketState,
    RuleBookRiskGate,
)
from quant_execution.schemas import (
    ACCOUNT_SNAPSHOT_SCHEMA_ID,
    FEE_SCHEMA_ID,
    FILL_SCHEMA_ID,
    FUNDING_SCHEMA_ID,
    LEDGER_TRANSACTION_SCHEMA_ID,
    LEGACY_SCHEMA_VERSION,
    ORDER_EVENT_SCHEMA_ID,
    ORDER_INTENT_SCHEMA_ID,
    ORDER_SCHEMA_ID,
    RUN_RESULT_SCHEMA_ID,
    SCHEMA_VERSION,
    SETTLEMENT_SCHEMA_ID,
    execution_payload,
    get_arrow_schema,
    get_json_schema,
    validate_arrow_table,
    validate_json_record,
)
from quant_execution.state_machine import ALLOWED_TRANSITIONS, transition_order

__version__ = "0.5.0"

__all__ = [
    "ACCOUNT_SNAPSHOT_SCHEMA_ID",
    "ALLOWED_TRANSITIONS",
    "FEE_SCHEMA_ID",
    "FILL_SCHEMA_ID",
    "FUNDING_SCHEMA_ID",
    "LEDGER_TRANSACTION_SCHEMA_ID",
    "LEGACY_SCHEMA_VERSION",
    "ORDER_EVENT_SCHEMA_ID",
    "ORDER_INTENT_SCHEMA_ID",
    "ORDER_SCHEMA_ID",
    "RUN_RESULT_SCHEMA_ID",
    "SCHEMA_VERSION",
    "SETTLEMENT_SCHEMA_ID",
    "AShareRule",
    "AccountLedger",
    "AccountSnapshot",
    "ArrowReplayArtifactSink",
    "BarMatchingModel",
    "BrokerSimulator",
    "CryptoSpotRule",
    "DeterministicBroker",
    "DeterministicRunEngine",
    "ExactAccountLedger",
    "Fee",
    "Fill",
    "Funding",
    "FuturesRule",
    "L2MatchingModel",
    "LedgerEvent",
    "LedgerEventType",
    "LedgerTransaction",
    "LinearPerpetualRule",
    "LiquidityRole",
    "MarketState",
    "MatchingModel",
    "Order",
    "OrderEvent",
    "OrderIntent",
    "OrderStatus",
    "OrderType",
    "PortfolioRiskPolicy",
    "PortfolioRiskSnapshot",
    "PositionRiskSnapshot",
    "Posting",
    "ReplayError",
    "RiskCheckContext",
    "RiskDecision",
    "RiskGate",
    "RuleBookRiskGate",
    "RunArtifacts",
    "RunEngine",
    "RunResult",
    "Settlement",
    "Side",
    "StoredRunArtifacts",
    "Strategy",
    "StrategyContext",
    "TimeInForce",
    "TradeBBOModel",
    "execution_payload",
    "get_arrow_schema",
    "get_json_schema",
    "load_stored_artifacts",
    "remaining_quantity",
    "transition_order",
    "validate_arrow_table",
    "validate_json_record",
]
