"""Deterministic execution contracts for PureSaber."""

from quant_execution.contracts import (
    AccountSnapshot,
    Fee,
    Fill,
    Funding,
    LedgerEvent,
    LedgerEventType,
    LedgerTransaction,
    LiquidityRole,
    Order,
    OrderEvent,
    OrderIntent,
    OrderStatus,
    OrderType,
    Posting,
    RiskDecision,
    RunResult,
    Settlement,
    Side,
    TimeInForce,
)
from quant_execution.protocols import (
    AccountLedger,
    BrokerSimulator,
    MatchingModel,
    RiskGate,
    RunEngine,
    Strategy,
    StrategyContext,
)
from quant_execution.schemas import (
    FEE_SCHEMA_ID,
    FILL_SCHEMA_ID,
    FUNDING_SCHEMA_ID,
    LEDGER_TRANSACTION_SCHEMA_ID,
    ORDER_EVENT_SCHEMA_ID,
    ORDER_INTENT_SCHEMA_ID,
    ORDER_SCHEMA_ID,
    SETTLEMENT_SCHEMA_ID,
    execution_payload,
    get_arrow_schema,
    get_json_schema,
    validate_arrow_table,
    validate_json_record,
)
from quant_execution.state_machine import ALLOWED_TRANSITIONS, transition_order

__version__ = "0.1.0"

__all__ = [
    "ALLOWED_TRANSITIONS",
    "FEE_SCHEMA_ID",
    "FILL_SCHEMA_ID",
    "FUNDING_SCHEMA_ID",
    "LEDGER_TRANSACTION_SCHEMA_ID",
    "ORDER_EVENT_SCHEMA_ID",
    "ORDER_INTENT_SCHEMA_ID",
    "ORDER_SCHEMA_ID",
    "SETTLEMENT_SCHEMA_ID",
    "AccountLedger",
    "AccountSnapshot",
    "BrokerSimulator",
    "Fee",
    "Fill",
    "Funding",
    "LedgerEvent",
    "LedgerEventType",
    "LedgerTransaction",
    "LiquidityRole",
    "MatchingModel",
    "Order",
    "OrderEvent",
    "OrderIntent",
    "OrderStatus",
    "OrderType",
    "Posting",
    "RiskDecision",
    "RiskGate",
    "RunEngine",
    "RunResult",
    "Settlement",
    "Side",
    "Strategy",
    "StrategyContext",
    "TimeInForce",
    "execution_payload",
    "get_arrow_schema",
    "get_json_schema",
    "transition_order",
    "validate_arrow_table",
    "validate_json_record",
]
